import logging
import uuid
from datetime import datetime, timezone

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.documents import ScenarioDemoFrame

logger = logging.getLogger(__name__)

STORM_SCENARIO = {
    "scenario_id": "storm-impact-2024",
    "title": "기상 악화 → 선석 사용불가 → 체선 증가",
    "description": "태풍 접근에 따른 단계적 항만 운영 영향 시나리오",
    "duration_seconds": 28800,
    "frames": [
        {
            "frame_index": 0,
            "timestamp": "2024-08-15T06:00:00Z",
            "weather": {
                "wind_speed": 8.0,
                "wind_dir": 180,
                "temperature": 28.5,
                "humidity": 72,
                "pressure": 1013,
                "precipitation": 0,
                "visibility": 10,
                "wave_height": 0.8,
            },
            "berth_statuses": [
                {"facility_code": "UB01", "status": "normal"},
                {"facility_code": "UB02", "status": "normal"},
                {"facility_code": "UB03", "status": "normal"},
                {"facility_code": "UB04", "status": "normal"},
                {"facility_code": "UB05", "status": "normal"},
            ],
            "vessel_positions": [
                {
                    "vessel_id": "V001",
                    "name": "한진울산",
                    "lat": 35.502,
                    "lon": 129.381,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V002",
                    "name": "현대석유",
                    "lat": 35.498,
                    "lon": 129.375,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V003",
                    "name": "SK에너지호",
                    "lat": 35.510,
                    "lon": 129.390,
                    "speed": 5.2,
                    "course": 225,
                    "ship_type": "tanker",
                },
            ],
            "alerts": [],
            "ai_summary": "정상 운영 중입니다. 기상 양호, 전 선석 정상 가동, 체선 없음.",
        },
        {
            "frame_index": 1,
            "timestamp": "2024-08-15T07:00:00Z",
            "weather": {
                "wind_speed": 12.0,
                "wind_dir": 195,
                "temperature": 27.8,
                "humidity": 78,
                "pressure": 1010,
                "precipitation": 2,
                "visibility": 8,
                "wave_height": 1.2,
            },
            "berth_statuses": [
                {"facility_code": "UB01", "status": "normal"},
                {"facility_code": "UB02", "status": "normal"},
                {"facility_code": "UB03", "status": "normal"},
                {"facility_code": "UB04", "status": "normal"},
                {"facility_code": "UB05", "status": "normal"},
            ],
            "vessel_positions": [
                {
                    "vessel_id": "V001",
                    "name": "한진울산",
                    "lat": 35.502,
                    "lon": 129.381,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V002",
                    "name": "현대석유",
                    "lat": 35.498,
                    "lon": 129.375,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V003",
                    "name": "SK에너지호",
                    "lat": 35.507,
                    "lon": 129.387,
                    "speed": 3.1,
                    "course": 225,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V004",
                    "name": "대한케미컬",
                    "lat": 35.515,
                    "lon": 129.395,
                    "speed": 7.0,
                    "course": 210,
                    "ship_type": "chemical",
                },
            ],
            "alerts": [],
            "ai_summary": "풍속 상승 추세(12m/s). 입항 예정 선박에 주의보를 전달하십시오.",
        },
        {
            "frame_index": 2,
            "timestamp": "2024-08-15T08:00:00Z",
            "weather": {
                "wind_speed": 17.5,
                "wind_dir": 200,
                "temperature": 26.5,
                "humidity": 85,
                "pressure": 1006,
                "precipitation": 15,
                "visibility": 4,
                "wave_height": 2.3,
            },
            "berth_statuses": [
                {"facility_code": "UB01", "status": "normal"},
                {"facility_code": "UB02", "status": "normal"},
                {"facility_code": "UB03", "status": "damaged"},
                {"facility_code": "UB04", "status": "normal"},
                {"facility_code": "UB05", "status": "normal"},
            ],
            "vessel_positions": [
                {
                    "vessel_id": "V001",
                    "name": "한진울산",
                    "lat": 35.502,
                    "lon": 129.381,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V002",
                    "name": "현대석유",
                    "lat": 35.498,
                    "lon": 129.375,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V003",
                    "name": "SK에너지호",
                    "lat": 35.505,
                    "lon": 129.385,
                    "speed": 1.0,
                    "course": 180,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V004",
                    "name": "대한케미컬",
                    "lat": 35.512,
                    "lon": 129.392,
                    "speed": 2.0,
                    "course": 210,
                    "ship_type": "chemical",
                },
                {
                    "vessel_id": "V005",
                    "name": "동방가스",
                    "lat": 35.520,
                    "lon": 129.400,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "gas",
                },
            ],
            "alerts": [
                {"type": "weather", "severity": "warning", "message": "풍속 17.5m/s — 운항 주의"},
                {"type": "weather", "severity": "warning", "message": "파고 2.3m — 접안 주의"},
            ],
            "ai_summary": "기상 경보 발생. 풍속 17.5m/s, 파고 2.3m. UB03 선석 일부 파손 확인. 접안 작업 주의 요망.",
        },
        {
            "frame_index": 3,
            "timestamp": "2024-08-15T09:00:00Z",
            "weather": {
                "wind_speed": 22.0,
                "wind_dir": 210,
                "temperature": 25.0,
                "humidity": 92,
                "pressure": 1002,
                "precipitation": 35,
                "visibility": 2,
                "wave_height": 3.1,
            },
            "berth_statuses": [
                {"facility_code": "UB01", "status": "normal"},
                {"facility_code": "UB02", "status": "unavailable"},
                {"facility_code": "UB03", "status": "unavailable"},
                {"facility_code": "UB04", "status": "damaged"},
                {"facility_code": "UB05", "status": "normal"},
            ],
            "vessel_positions": [
                {
                    "vessel_id": "V001",
                    "name": "한진울산",
                    "lat": 35.502,
                    "lon": 129.381,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V002",
                    "name": "현대석유",
                    "lat": 35.498,
                    "lon": 129.375,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V003",
                    "name": "SK에너지호",
                    "lat": 35.505,
                    "lon": 129.385,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V004",
                    "name": "대한케미컬",
                    "lat": 35.512,
                    "lon": 129.392,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "chemical",
                },
                {
                    "vessel_id": "V005",
                    "name": "동방가스",
                    "lat": 35.520,
                    "lon": 129.400,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "gas",
                },
                {
                    "vessel_id": "V006",
                    "name": "삼성중공업호",
                    "lat": 35.525,
                    "lon": 129.405,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "bulk",
                },
            ],
            "alerts": [
                {"type": "weather", "severity": "critical", "message": "풍속 22m/s — 입출항 제한"},
                {
                    "type": "weather",
                    "severity": "critical",
                    "message": "파고 3.1m — 접안 중단 권고",
                },
                {"type": "berth", "severity": "warning", "message": "사용불가 선석 2개"},
                {
                    "type": "compound",
                    "severity": "critical",
                    "message": "기상 악화 + 선석 불가 복합 위험",
                },
            ],
            "ai_summary": "위험 상황. 풍속 22m/s, 파고 3.1m로 입출항 제한. UB02, UB03 사용불가, UB04 파손. 체선 시작(대기 3척).",
        },
        {
            "frame_index": 4,
            "timestamp": "2024-08-15T10:00:00Z",
            "weather": {
                "wind_speed": 25.0,
                "wind_dir": 215,
                "temperature": 24.0,
                "humidity": 95,
                "pressure": 999,
                "precipitation": 50,
                "visibility": 1,
                "wave_height": 3.8,
            },
            "berth_statuses": [
                {"facility_code": "UB01", "status": "damaged"},
                {"facility_code": "UB02", "status": "unavailable"},
                {"facility_code": "UB03", "status": "unavailable"},
                {"facility_code": "UB04", "status": "unavailable"},
                {"facility_code": "UB05", "status": "damaged"},
            ],
            "vessel_positions": [
                {
                    "vessel_id": "V001",
                    "name": "한진울산",
                    "lat": 35.502,
                    "lon": 129.381,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V002",
                    "name": "현대석유",
                    "lat": 35.498,
                    "lon": 129.375,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V003",
                    "name": "SK에너지호",
                    "lat": 35.505,
                    "lon": 129.385,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V004",
                    "name": "대한케미컬",
                    "lat": 35.512,
                    "lon": 129.392,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "chemical",
                },
                {
                    "vessel_id": "V005",
                    "name": "동방가스",
                    "lat": 35.520,
                    "lon": 129.400,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "gas",
                },
                {
                    "vessel_id": "V006",
                    "name": "삼성중공업호",
                    "lat": 35.525,
                    "lon": 129.405,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "bulk",
                },
                {
                    "vessel_id": "V007",
                    "name": "포스코물류",
                    "lat": 35.530,
                    "lon": 129.410,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "bulk",
                },
                {
                    "vessel_id": "V008",
                    "name": "롯데케미칼호",
                    "lat": 35.518,
                    "lon": 129.398,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "chemical",
                },
            ],
            "alerts": [
                {
                    "type": "weather",
                    "severity": "critical",
                    "message": "풍속 25m/s — 전면 입출항 금지",
                },
                {
                    "type": "berth",
                    "severity": "critical",
                    "message": "사용불가 선석 3개 — 비상 운영",
                },
                {"type": "congestion", "severity": "warning", "message": "체선 5척 — 체선 심화"},
                {
                    "type": "compound",
                    "severity": "critical",
                    "message": "태풍 접근으로 항만 운영 전면 중단",
                },
            ],
            "ai_summary": "태풍 최근접. 풍속 25m/s, 파고 3.8m. 전면 입출항 금지. 3개 선석 사용불가. 대기 선박 5척으로 체선 급증.",
        },
        {
            "frame_index": 5,
            "timestamp": "2024-08-15T12:00:00Z",
            "weather": {
                "wind_speed": 18.0,
                "wind_dir": 220,
                "temperature": 25.5,
                "humidity": 88,
                "pressure": 1004,
                "precipitation": 20,
                "visibility": 5,
                "wave_height": 2.5,
            },
            "berth_statuses": [
                {"facility_code": "UB01", "status": "damaged"},
                {"facility_code": "UB02", "status": "unavailable"},
                {"facility_code": "UB03", "status": "unavailable"},
                {"facility_code": "UB04", "status": "checking"},
                {"facility_code": "UB05", "status": "normal"},
            ],
            "vessel_positions": [
                {
                    "vessel_id": "V001",
                    "name": "한진울산",
                    "lat": 35.502,
                    "lon": 129.381,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V002",
                    "name": "현대석유",
                    "lat": 35.498,
                    "lon": 129.375,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V003",
                    "name": "SK에너지호",
                    "lat": 35.505,
                    "lon": 129.385,
                    "speed": 1.5,
                    "course": 180,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V004",
                    "name": "대한케미컬",
                    "lat": 35.512,
                    "lon": 129.392,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "chemical",
                },
                {
                    "vessel_id": "V005",
                    "name": "동방가스",
                    "lat": 35.520,
                    "lon": 129.400,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "gas",
                },
                {
                    "vessel_id": "V006",
                    "name": "삼성중공업호",
                    "lat": 35.525,
                    "lon": 129.405,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "bulk",
                },
            ],
            "alerts": [
                {
                    "type": "weather",
                    "severity": "warning",
                    "message": "풍속 감소 중(18m/s) — 아직 주의 필요",
                },
            ],
            "ai_summary": "기상 회복 시작. 풍속 18m/s로 하락 추세. UB04 점검 중, UB05 정상 복구. 접안 재개 검토 가능.",
        },
        {
            "frame_index": 6,
            "timestamp": "2024-08-15T14:00:00Z",
            "weather": {
                "wind_speed": 10.0,
                "wind_dir": 230,
                "temperature": 27.0,
                "humidity": 75,
                "pressure": 1009,
                "precipitation": 3,
                "visibility": 8,
                "wave_height": 1.5,
            },
            "berth_statuses": [
                {"facility_code": "UB01", "status": "normal"},
                {"facility_code": "UB02", "status": "checking"},
                {"facility_code": "UB03", "status": "unavailable"},
                {"facility_code": "UB04", "status": "normal"},
                {"facility_code": "UB05", "status": "normal"},
            ],
            "vessel_positions": [
                {
                    "vessel_id": "V001",
                    "name": "한진울산",
                    "lat": 35.502,
                    "lon": 129.381,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V002",
                    "name": "현대석유",
                    "lat": 35.498,
                    "lon": 129.375,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V003",
                    "name": "SK에너지호",
                    "lat": 35.501,
                    "lon": 129.380,
                    "speed": 0,
                    "course": 0,
                    "ship_type": "tanker",
                },
                {
                    "vessel_id": "V004",
                    "name": "대한케미컬",
                    "lat": 35.504,
                    "lon": 129.383,
                    "speed": 2.0,
                    "course": 190,
                    "ship_type": "chemical",
                },
            ],
            "alerts": [],
            "ai_summary": "정상 복귀 진행 중. 풍속 10m/s, 3개 선석 정상. UB02 점검 중, UB03은 수리 필요. 체선 해소 시작.",
        },
    ],
}


async def seed_scenario_frames(session: AsyncSession) -> int:
    scenario = STORM_SCENARIO
    count = 0

    for frame_data in scenario["frames"]:
        frame = ScenarioDemoFrame(
            frame_id=uuid.uuid4(),
            scenario_id=scenario["scenario_id"],
            frame_index=frame_data["frame_index"],
            timestamp=frame_data["timestamp"],
            vessel_positions=frame_data["vessel_positions"],
            berth_statuses=frame_data["berth_statuses"],
            weather=frame_data["weather"],
            alerts=frame_data["alerts"],
            ai_summary=frame_data["ai_summary"],
            is_simulated=True,
        )
        session.add(frame)
        count += 1

    await session.commit()
    return count


def get_scenario_metadata() -> dict:
    s = STORM_SCENARIO
    return {
        "scenario_id": s["scenario_id"],
        "title": s["title"],
        "description": s["description"],
        "duration_seconds": s["duration_seconds"],
        "frame_count": len(s["frames"]),
    }
